//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaberPortal.Database.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Trafik
    {
        public int Id { get; set; }
        public string ip { get; set; }
        public Nullable<System.DateTime> GirisTarih { get; set; }
        public string Tur { get; set; }
        public Nullable<System.TimeSpan> GirisSaat { get; set; }
    }
}
