//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaberPortal.Database.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Haberler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Haberler()
        {
            this.tbl_Begeni = new HashSet<tbl_Begeni>();
            this.tbl_HaberResim = new HashSet<tbl_HaberResim>();
            this.tbl_Paylasildi = new HashSet<tbl_Paylasildi>();
            this.tbl_Yorum = new HashSet<tbl_Yorum>();
        }
    
        public int Id { get; set; }
        public string AnaBaslik { get; set; }
        public string HaberOzet { get; set; }
        public string HaberYazisi { get; set; }
        public Nullable<System.DateTime> YayinTarihi { get; set; }
        public Nullable<int> BeğeniSayisi { get; set; }
        public Nullable<int> YorumSayisi { get; set; }
        public Nullable<int> Paylasildi { get; set; }
        public Nullable<int> YazarNo { get; set; }
        public byte[] BaslikResim { get; set; }
        public string Tur { get; set; }
        public Nullable<System.TimeSpan> YayinSaati { get; set; }
        public Nullable<int> KategoriNo { get; set; }
        public Nullable<int> Okundu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Begeni> tbl_Begeni { get; set; }
        public virtual tbl_Yazarlar tbl_Yazarlar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_HaberResim> tbl_HaberResim { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Paylasildi> tbl_Paylasildi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Yorum> tbl_Yorum { get; set; }
        public virtual tbl_Kategori tbl_Kategori { get; set; }
    }
}
