//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaberPortal.Database.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Begeni
    {
        public int Id { get; set; }
        public int UyeNo { get; set; }
        public int HaberNo { get; set; }
    
        public virtual tbl_Haberler tbl_Haberler { get; set; }
        public virtual tbl_Uye tbl_Uye { get; set; }
    }
}
